set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/${PROJECT_NAME})
set(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/${PROJECT_NAME})

set(NACS_THIRDPARTY "${CMAKE_CURRENT_SOURCE_DIR}/3rd")
if (CMAKE_CL_64)
  set(NACS_PLATFORM x64)
else ()
  set(NACS_PLATFORM x86)
endif ()

if (UNIX)
	set(CMAKE_CXX_FLAGS "-Wl,-rpath=./")
	set(CMAKE_C_FLAGS "-Wl,-rpath=./")
elseif (MSVC)
	add_compile_options("/utf-8")
	add_compile_definitions(UNICODE _UNICODE)
endif()
