function (FindTargetDependencies target output)
	get_target_property(link_libs ${target} LINK_LIBRARIES)
	foreach (link_lib ${link_libs})
		if (link_lib)
			list(APPEND ${output} ${link_lib})
			FindTargetDependencies(${link_lib} ${output})
		endif ()
	endforeach ()
	set(${output} ${${output}} PARENT_SCOPE)
endfunction ()

function (FindTargetLibraries target output)
    foreach(depend_target ${${target}})
        if (TOP_DEBUG)
            get_target_property(depend_location ${depend_target} IMPORTED_LOCATION_DEBUG)
        else ()
            get_target_property(depend_location ${depend_target} IMPORTED_LOCATION_RELEASE)
        endif ()
        if (depend_location)
            list(APPEND output ${depend_location})
        endif()
    endforeach()
    set(${output} ${${output}} PARENT_SCOPE)
endfunction()
